### ISSUE TITLE
Docker Compose issues

### ISSUE THREAD

**Issue by ItsNoted** [Ge0rg3e/Collectarr#1]
Hey! Just wanting to test it out and when I ran the docker compose last night I was getting an error. Is there a way to fix rhis?

```
Error
    at Database.<anonymous> (/app/Collectarr/server/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /app/Collectarr/server/node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/app/Collectarr/server/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /app/Collectarr/server/node_modules/sequelize/lib/sequelize.js:315:28
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SQLiteQueryInterface.select (/app/Collectarr/server/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Accounts.findAll (/app/Collectarr/server/node_modules/sequelize/lib/model.js:1140:21)
    at async handler (/app/Collectarr/server/dist/tasks/temporaryAccounts.js:22:31)
    at async _default (/app/Collectarr/server/dist/tasks/temporaryAccounts.js:43:5) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: no such table: accounts] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `id`, `username`, `temporary` FROM `accounts` AS `Accounts` WHERE `Accounts`.`temporary` IS NOT NULL;'
  },
  original: [Error: SQLITE_ERROR: no such table: accounts] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'SELECT `id`, `username`, `temporary` FROM `accounts` AS `Accounts` WHERE `Accounts`.`temporary` IS NOT NULL;'
  },
  sql: 'SELECT `id`, `username`, `temporary` FROM `accounts` AS `Accounts` WHERE `Accounts`.`temporary` IS NOT NULL;',
  parameters: {}
}
Node.js v18.17.0
```

**Comment by Ge0rg3e** [comment]
Hello, thank you for the report, I will fix this as soon as possible.

**Comment by Ge0rg3e** [comment]
The issue has been resolved. Please come back with another message if you encounter any further errors 🙂

**Comment by ItsNoted** [comment]
Does it have to have these values to work?

```
- TUNNEL= # {ngrok}
- TUNNEL_AUTH= # {token} - Mandatory for ngrok
- FORCE_RESET= # {password} - This option is used to reset the password of the main account.
```

**Comment by Ge0rg3e** [comment]
Hello, those values are completely optional.

**Comment by ItsNoted** [comment]
Ok because I am still getting the same error when running the docker compose.

**Comment by Ge0rg3e** [comment]
Use ``docker pull ge0rg3e/collectarr`` to update the image.
